### ISSUE TITLE
matrix daugther boards

### ISSUE THREAD

**Issue by eljuligallego** [Nerdaxic/GLaDOS-Voice-Assistant#1]
Hi,
I have a matrix creator and would like to give a try with my board but I guess I have to change lot of code.

have our consider to use the matrix products instead of the respeaker?.

they include rgb leds ring and more sensors and leave the raspberry pinout accesible fo the eye lcd(even they include and extra atmel micro controller for development).

**Comment by Nerdaxic** [comment]
Not familiar with Matrix boards no. I already have the hardware built, so I'll probably not support other platforms that what I have listed here. Feel free to fork though!
