### ISSUE TITLE
Trying to try the TTS and it has an error

### ISSUE THREAD

**Issue by 12tae12** [nerdaxic/glados-voice-assistant#35]
`user@userPC:~/glados-voice-assistant/glados_tts$ sudo python3 glados.py
Initializing TTS Engine...
[W NNPACK.cpp:79] Could not initialize NNPACK! Reason: Unsupported hardware.
Input: The odd ones out
Forward Tacotron took 919.8753833770752ms
HiFiGAN took 4246.425151824951ms
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
aplay: main:852: audio open error: No such file or directory
`

Whats going on.. Please help.

**Comment by eternalliving** [comment]
Are you trying to run it on a raspberry pi? It looks like it is still trying to load the TTS engine, which it shouldn't, as you would be using glados.c-net.org as your tts engine right?

**Comment by 12tae12** [comment]
No

**Comment by 12tae12** [comment]
Its not i just finished reinstalling.
