### ISSUE TITLE
Feature Request: Alternate wake word "GLaDOS" in addition to "Hey GLaDOS"

### ISSUE THREAD

**Issue by dannyvfilms** [nerdaxic/glados-voice-assistant#41]
I'm getting used to Siri not needing "Hey" anymore in the wake word phrase, so it would be great if possible to have an additional wake word of just "GLaDOS" as well as "Hey GLaDOS" to choose from.

**Comment by nerdaxic** [comment]
Solved in Ollama push using OpenWakeWord. It triggers on both.
